#!/usr/bin/env python3
"""
ToolsNova — Related Tools injector (Phase 3.6, Task 9 + internal linking)
===========================================================================
NEW script. Does not touch generator.py or pages_generator.py.

Injects a "Related Tools" section into every tool page, right before
</main> (i.e. after the tool's own content, before the shared footer).
Does NOT touch each tool's calculator/generator <script> logic — pure
HTML insertion using the existing .related-tools-section / .related-grid
/ .related-card CSS classes (already defined in cards.css, unmodified).

Relatedness is computed purely from tools.json's `category` field —
same category, excluding self, capped at 6. Never hardcoded per-tool.
Also appends a "Browse all N {category} tools" link back to the new
category landing page, completing the
  Tool page -> Related Tools -> Back to Category
part of the internal-linking chain requested for Phase 3.6.

Idempotent: running twice does not duplicate the section (it replaces
any previously-injected block, marked by HTML comments).

Usage:
  python3 inject_related_tools.py            # inject into all tool pages
  python3 inject_related_tools.py --dry-run  # report only, no writes
"""

import json, re
from pathlib import Path

BASE_DIR = Path(__file__).parent
DATA_DIR = BASE_DIR / 'data'

CATEGORY_SLUGS = {
    'Developer': 'developer-tools', 'Finance': 'finance-tools', 'Trading': 'trading-tools',
    'Utilities': 'utilities', 'Health': 'health-tools', 'Students': 'student-tools',
    'Construction': 'construction-tools', 'Converters': 'converter-tools', 'AI': 'ai-tools',
    'Math': 'math-tools', 'Prop Firm': 'prop-firm-tools', 'Fun': 'fun-tools',
}

START_MARKER = '<!-- RELATED-TOOLS:START (auto-generated by inject_related_tools.py — do not hand-edit) -->'
END_MARKER   = '<!-- RELATED-TOOLS:END -->'

# Many tool pages (132 of 147, found during Phase 3.6 verification) already
# contained an OLDER, hand-hardcoded "Related Tools" block — specific tool
# names typed directly into the HTML, not derived from tools.json. This
# violates "generated automatically, never hardcoded" and, left in place
# alongside the new dynamic block, produces a visibly duplicated section.
# This pattern removes the old block before inserting the new one.
OLD_BLOCK_RE = re.compile(
    r'<section class="related-section">\s*'
    r'<h2 class="related-title">Related Tools</h2>\s*'
    r'<div class="related-grid">.*?</div>\s*'
    r'</section>',
    re.DOTALL
)

# A SECOND, different old hand-hardcoded pattern — "Template B" — was
# found on 6 newer tool pages (added after the original 148-page
# migration batch) during a structural audit. Template B is a bare
# <div class="related-tools-section"> wrapper (NOT nested inside an
# edu-section, and NOT the <section class="related-section"> of
# Template A above) containing an <h2 class="related-title">Related
# {category} tools</h2> heading followed by a related-grid div.
# Confirmed via direct inspection of all 6 affected pages before
# writing this pattern — see Phase 3.6 CHANGELOG entry for the audit.
OLD_BLOCK_RE_2 = re.compile(
    r'<div class="related-tools-section">\s*'
    r'<h2 class="related-title">Related[^<]*</h2>\s*'
    r'<div class="related-grid">.*?</div>\s*'
    r'</div>',
    re.DOTALL
)

def he(s):
    return str(s).replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;').replace('"', '&quot;')

def build_block(tool, related, category_slug, category_name, category_count):
    cards = "\n    ".join(
        f'<a class="related-card" href="{he(r["url"])}">'
        f'<span class="rc-icon">{r.get("icon","🔧")}</span>'
        f'<div><div class="rc-name">{he(r["name"])}</div><div class="rc-desc">{he(r.get("desc","")[:70])}</div></div>'
        f'</a>' for r in related
    )
    browse_link = (
        f'<a href="{category_slug}/index.html" class="section-view-all" '
        f'style="display:inline-block;margin-top:.75rem">Browse all {category_count}+ {he(category_name)} tools →</a>'
        if category_slug else ''
    )
    return f"""{START_MARKER}
<section class="related-tools-section">
  <div class="related-title">🔗 Related Tools</div>
  <div class="related-grid">
    {cards}
  </div>
  {browse_link}
</section>
{END_MARKER}"""

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--dry-run', action='store_true')
    args = parser.parse_args()

    tools = json.load(open(DATA_DIR / 'tools.json'))
    by_category = {}
    for t in tools:
        by_category.setdefault(t['category'], []).append(t)

    updated = 0
    skipped_no_file = []
    skipped_no_main = []

    for tool in tools:
        path = BASE_DIR / tool['url']
        if not path.exists():
            skipped_no_file.append(tool['url'])
            continue

        content = path.read_text(encoding='utf-8')

        # Remove any previously-injected block (idempotency)
        content = re.sub(
            re.escape(START_MARKER) + r'.*?' + re.escape(END_MARKER),
            '', content, flags=re.DOTALL
        )

        # Remove the OLD hand-hardcoded related-tools block, if present
        # (found on 132/147 pages during Phase 3.6 verification — see
        # module docstring). Prevents a duplicated "Related Tools" section.
        old_removed = bool(OLD_BLOCK_RE.search(content))
        content = OLD_BLOCK_RE.sub('', content)
        content = OLD_BLOCK_RE_2.sub('', content)

        if '</main>' not in content:
            skipped_no_main.append(tool['url'])
            continue

        same_cat = [t for t in by_category.get(tool['category'], []) if t['url'] != tool['url']]
        related = same_cat[:6]
        if not related:
            continue  # a category with only 1 tool has nothing to relate to

        cat_slug = CATEGORY_SLUGS.get(tool['category'])
        cat_count = len(by_category.get(tool['category'], []))
        block = build_block(tool, related, cat_slug, tool['category'], cat_count)

        content = content.replace('</main>', block + '\n</main>', 1)

        if not args.dry_run:
            path.write_text(content, encoding='utf-8')
        updated += 1

    print(f"{'[DRY RUN] ' if args.dry_run else ''}Related Tools injection complete:")
    print(f"  Pages updated: {updated} / {len(tools)}")
    if skipped_no_file:
        print(f"  Skipped (file not found): {len(skipped_no_file)} -> {skipped_no_file[:5]}{'...' if len(skipped_no_file)>5 else ''}")
    if skipped_no_main:
        print(f"  Skipped (no </main> tag found): {len(skipped_no_main)} -> {skipped_no_main[:5]}{'...' if len(skipped_no_main)>5 else ''}")

if __name__ == '__main__':
    main()
